import { Helmet } from 'react-helmet-async';
// @mui
import { Avatar, Badge, Box, Container, IconButton, Stack, Typography } from '@mui/material';
// components
import TwitterIcon from '@mui/icons-material/Twitter';
import LinkedinIcon from '@mui/icons-material/LinkedIn';
import InstagramIcon from '@mui/icons-material/Instagram';
import { styled } from '@mui/material/styles';
import GitHubIcon from '@mui/icons-material/GitHub';
import { useSettingsContext } from '../components/settings';

// ----------------------------------------------------------------------

export default function PageWelcome() {
  const { themeStretch } = useSettingsContext();
  const StyledBadge = styled(Badge)(({ theme }) => ({
    '& .MuiBadge-badge': {
      backgroundColor: '#44b700',
      color: '#44b700',
      boxShadow: `0 0 0 2px ${theme.palette.background.paper}`,
      '&::after': {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        borderRadius: '50%',
        animation: 'ripple 1.2s infinite ease-in-out',
        border: '1px solid currentColor',
        content: '""',
      },
    },
    '@keyframes ripple': {
      '0%': {
        transform: 'scale(.8)',
        opacity: 1,
      },
      '100%': {
        transform: 'scale(2.4)',
        opacity: 0,
      },
    },
  }));

  const subtitle1 = "Why 'Pictolabis'";

  const paragraph3_1 =
    "'Picto' which is derived from picture or image, together with 'lab' which is derived from laboratory, together is a 'Picto Laboratory'.";
  const paragraph3_2 =
    "On the other hand, it also draws a similarity to 'Piscolabis', a term that comes from Spain, that means a light snack or appetizer. Thus, 'Pictolabis' could be interpreted as a tool or platform that provides bite-sized, appetizing prompts for generating images or pictures.";

  const paragraph4 =
    'Whether you are a professional artist or just someone who loves to create, our web app is here to support your creative process by generating prompts that will ignite your imagination.🔥.';

  const paragraph5 =
    'The app could offer a variety of creative prompts, such as keywords, phrases, or visual cues, that can inspire users to come up with original and imaginative ideas for generating images using AI or other tools.It could serve as a catalyst for sparking creativity and pushing the boundaries of what is possible in image generation, just like how a tasty appetizer can whet your appetite for more culinary delights.';
  const paragraph6 =
    'Overall, we aim to be a fun, engaging, and helpful resource for artists and to enhance creativity on their image generation process and unlock new creative possibilities.';
  return (
    <>
      <Helmet>
        <title> Welcome</title>
      </Helmet>

      <Container maxWidth={themeStretch ? false : 'md'}>
        <Typography variant="h3" component="h1" paragraph>
          Welcome
        </Typography>
      </Container>
      <Container maxWidth={themeStretch ? false : 'md'} sx={{ marginTop: '20px' }}>
        <Typography gutterBottom>
          Welcome Pictolabis! The ultimate image prompt generator.
        </Typography>
        <Typography gutterBottom>
          We are thrilled to have you here, and we are sure that you will find our tool to be a
          valuable resource for your artistic endeavors.
        </Typography>

        <Typography gutterBottom variant="h6" marginTop={2}>
          What is this?
        </Typography>

        <Typography gutterBottom>
          We are an app designed to provide you with unique and inspiring prompts that will spark
          your creativity and help you write original descriptions for images generated by AI.💡🤖
        </Typography>

        <Typography>{paragraph6}</Typography>

        <Typography gutterBottom variant="h6" marginTop={2}>
          {subtitle1}
        </Typography>
        <Typography>It is a creative and unique name for two 2 reasons:</Typography>
        <Typography>1.- {paragraph3_1}</Typography>

        <Typography>2.- {paragraph3_2}</Typography>

        <Typography gutterBottom variant="h6" marginTop={2}>
          Who is it for?
        </Typography>
        <Typography>{paragraph4}</Typography>
        <Typography>{paragraph5}</Typography>

        <Typography gutterBottom variant="h6" marginTop={2}>
          Enjoy!
        </Typography>
        <Typography gutterBottom>
          Get ready to explore endless possibilities and unlock your artistic potential with our
          image prompt generator. Happy creating! 🎨🌈
        </Typography>
      </Container>
    </>
  );
}
